### PR TITLE
Fix gradle lint.

### LINKED ISSUE #8: Fix gradle lint
Currently, lint reports the following issues:
```
  Errors found:
  
  /home/marcin/proj/android/QDict/qDict/src/main/java/com/mmt/app/SystemBarTintManager.java:104: Error: Expected resource of type styleable [ResourceType]
                  mNavBarAvailable = a.getBoolean(1, false);
                                                  ~
  /home/marcin/proj/android/QDict/qDict/src/main/java/com/mmt/widget/DragSortListView.java:2805: Error: Call requires API level 21 (current min is 17): android.widget.AbsListView#setSelectionFromTop [NewApi]
              setSelectionFromTop(movePos, top - padTop);
              ~~~~~~~~~~~~~~~~~~~
  /home/marcin/proj/android/QDict/qDict/src/main/java/com/annie/dictionary/standout/StandOutWindow.java:583: Error: Must be one or more of: PendingIntent.FLAG_ONE_SHOT, PendingIntent.FLAG_NO_CREATE, PendingIntent.FLAG_CANCEL_CURRENT, PendingIntent.FLAG_UPDATE_CURRENT, PendingIntent.FLAG_IMMUTABLE, Intent.FILL_IN_ACTION, Intent.FILL_IN_DATA, Intent.FILL_IN_CATEGORIES, Intent.FILL_IN_COMPONENT, Intent.FILL_IN_PACKAGE, Intent.FILL_IN_SOURCE_BOUNDS, Intent.FILL_IN_SELECTOR, Intent.FILL_IN_CLIP_DATA [WrongConstant]
                      Intent.FLAG_ACTIVITY_NEW_TASK);
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by marmistrz**
Closes #8.

@yuhuitech would you mind reviewing this patch?

### CODE REVIEW

**Comment by EasyVector** [comment]
OK, I would love to. So I need to apply those changes and test them, right?

**Comment by marmistrz** [comment]
Reviewing usually means looking at the changes, trying to find any pitfalls or mistakes. I'm not sure about this StandOutWindow change because I haven't seen anything like that while using the app. It seems to be related to some service functionality of QDict but I didn't notice it either...

**Comment by marmistrz** [comment]
@yuhuitech any remarks regarding this change or can I merge it?

**Comment by EasyVector** [comment]
OK. Sorry for the late. I applied the changes you mentioned and I did not find anything wrong and my Android Studio also did not generate any fatal warning or error message. It seems good to me. :)

**Pull request merged**
